version: "3.8"
services:
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"  # Map port 8000 from the container to port 8000 on the host
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/postgres
    volumes:
      - .:/app  # Mount the current directory to the container's /app directory

volumes:
  timescaledb_data: