version: "3.8"
services:
  timescaledb:
    image: timescale/timescaledb-ha:pg16
    container_name: timescaledb
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - timescaledb_data:/var/lib/postgresql/data
    restart: unless-stopped


  
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"  # Map port 8000 from the container to port 8000 on the host
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://postgres:password@timescaledb:5432/postgres
    volumes:
      - .:/app  # Mount the current directory to the container's /app directory
    depends_on:
      - timescaledb 

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "443:443"  # Expose HTTPS port
      - "80:80"    # Expose HTTP port for redirection
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt  # Mount your certificates
      - ./certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - fastapi-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  timescaledb_data: